{
 "title": "Smart Devices Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "uht_table", "query": "etuhtsensor" },
   { "name": "lamp_table", "query": "etlamp" },
   { "name": "airconditioner_table", "query": "etairconditioner" },
   { "name": "doorsensor_table", "query": "etdoorsensor" },
   { "name": "vehicle_table", "query": "etvehicle" },
   { "name": "wifisensor_table", "query": "etwifisensor" },
   { "name": "doorlocker_table", "query": "etdoorlocker" },
   { "name": "currsensor_table", "query": "etcurrentsensor" },
   { "name": "gassensor_table", "query": "etgasdetector" },
   { "name": "nfcsensor_table", "query": "etnfcreader" },
   {
    "name": "uht_device",
    "label": "UHT Sensor",
    "query": "select entity_id from $uht_table"
   },
   {
    "name": "lamp_device",
    "label": "Lamp Actuator",
    "query": "select entity_id from $lamp_table"
   },
   {
    "name": "airconditioner_device",
    "label": "Air Conditioner Actuator",
    "query": "select entity_id from $airconditioner_table"
   },
   {
    "name": "doorlocker_device",
    "label": "Door Locker Actuator",
    "query": "select entity_id from $doorlocker_table"
   },
   {
    "name": "wifisensor_device",
    "label": "Wifi Sensor",
    "query": "select entity_id from $wifisensor_table"
   },
   {
    "name": "vehicle_device",
    "label": "Vehicle Position",
    "query": "select entity_id from $vehicle_table"
   },
   {
    "name": "doorsensor_device",
    "label": "Door Contact Sensor",
    "query": "select entity_id from $doorsensor_table"
   },
   { "name": "state_on", "query": "ON" },
   { "name": "state_off", "query": "OFF" },
   { "name": "state_lock", "query": "LOCKED" },
   { "name": "state_unlock", "query": "UNLOCKED" },
   { "name": "state_on_verb", "query": "Turn On" },
   { "name": "state_off_verb", "query": "Turn Off" },
   { "name": "state_lock_verb", "query": "Lock" },
   { "name": "state_unlock_verb", "query": "Unlock" }
  ]
 },
 "panels": [
  { "title": "Number of Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UHT Sensors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(DISTINCT entity_id)\r\nFROM $uht_table\r\nWHERE\r\n  $__timeFilter(time_index)"
    }
   ]
  },
  {
   "title": "Door Contact Sensors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(DISTINCT entity_id)\r\nFROM $doorsensor_table\r\nWHERE\r\n  $__timeFilter(time_index)"
    }
   ]
  },
  {
   "title": "WiFi Sensors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(DISTINCT entity_id)\r\nFROM $wifisensor_table\r\nWHERE\r\n  $__timeFilter(time_index)"
    }
   ]
  },
  {
   "title": "Vehicle Sensors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(DISTINCT entity_id)\r\nFROM $vehicle_table\r\nWHERE\r\n  $__timeFilter(time_index)"
    }
   ]
  },
  {
   "title": "Current Sensors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(DISTINCT entity_id)\r\nFROM $currsensor_table\r\nWHERE\r\n  $__timeFilter(time_index)"
    }
   ]
  },
  {
   "title": "Gas Detector Sensors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(DISTINCT entity_id)\r\nFROM $gassensor_table\r\nWHERE\r\n  $__timeFilter(time_index)"
    }
   ]
  },
  {
   "title": "NFC Sensors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(DISTINCT entity_id)\r\nFROM $nfcsensor_table\r\nWHERE\r\n  $__timeFilter(time_index)"
    }
   ]
  },
  {
   "title": "Lamp Actuators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(DISTINCT entity_id)\r\nFROM $lamp_table\r\nWHERE\r\n  $__timeFilter(time_index)"
    }
   ]
  },
  {
   "title": "Air Conditioner Actuators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(DISTINCT entity_id)\r\nFROM $airconditioner_table\r\nWHERE\r\n  $__timeFilter(time_index)"
    }
   ]
  },
  {
   "title": "Door Locker Actuators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(DISTINCT entity_id)\r\nFROM $doorlocker_table\r\nWHERE\r\n  $__timeFilter(time_index)"
    }
   ]
  },
  {
   "title": "UTH Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "UHT Sensor: $uht_device",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  time_index AS \"time\",\r\n  entity_id AS metric,\r\n  temperature\r\nFROM $uht_table t\r\nWHERE\r\n  $__timeFilter(time_index) and t.entity_id = '${uht_device:raw}'\r\nORDER BY 1,2"
      },
      {
       "rawSql": "SELECT\r\n  time_index AS \"time\",\r\n  entity_id AS metric,\r\n  humidity\r\nFROM $uht_table t\r\nWHERE\r\n  $__timeFilter(time_index) and t.entity_id = '${uht_device:raw}'\r\nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "Door Contact Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "$doorsensor_device",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  time_index AS \"time\",\r\n  doorcontact as \"State\"\r\nFROM $doorsensor_table t\r\nWHERE\r\n  $__timeFilter(time_index) and t.entity_id = '${doorsensor_device:raw}'\r\nORDER BY 1 desc\r\nLIMIT 100"
      }
     ]
    }
   ]
  },
  {
   "title": "WiFi Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of New Connections [15m]: $wifisensor_device",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroup(time_index, '15m') AS \"time\",  \r\n  entity_id AS metric,\r\n  count(personid) as value  \r\nFROM $wifisensor_table t \r\nWHERE $__timeFilter(time_index) and t.entity_id = '${wifisensor_device:raw}'  \r\nGROUP BY 1, 2\r\nORDER BY $__timeGroup(time_index, '15m')"
      }
     ]
    }
   ]
  },
  {
   "title": "Actuators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lamp Actuators List",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT DISTINCT time, entity_id as \"Device\", t.state as \"State\"\r\nFROM\r\n  (SELECT MAX(time_index) AS \"time\", entity_id as \"Device\"\r\n  FROM $lamp_table as t\r\n  WHERE $__timeFilter(time_index)\r\n  GROUP BY entity_id\r\n  ORDER BY MAX(time_index) desc) l, \r\n  $lamp_table t\r\nWHERE time = t.time_index AND entity_id = t.entity_id"
      }
     ]
    },
    {
     "title": "Air Conditioner Actuators List",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT DISTINCT time, entity_id as \"Device\", t.state as \"State\"\r\nFROM\r\n  (SELECT MAX(time_index) AS \"time\", entity_id as \"Device\"\r\n  FROM $airconditioner_table as t\r\n  WHERE $__timeFilter(time_index)\r\n  GROUP BY entity_id\r\n  ORDER BY MAX(time_index) desc) l, \r\n  $airconditioner_table t\r\nWHERE time = t.time_index AND entity_id = t.entity_id"
      }
     ]
    },
    {
     "title": "Door Locker Actuators List",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT DISTINCT time, entity_id as \"Device\", t.state as \"State\"\r\nFROM\r\n  (SELECT MAX(time_index) AS \"time\", entity_id as \"Device\"\r\n  FROM $doorlocker_table as t\r\n  WHERE $__timeFilter(time_index)\r\n  GROUP BY entity_id\r\n  ORDER BY MAX(time_index) desc) l, \r\n  $doorlocker_table t\r\nWHERE time = t.time_index AND entity_id = t.entity_id"
      }
     ]
    }
   ]
  },
  {
   "title": "Vehicle Tracking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "$vehicle_device",
     "type": "orchestracities-map-panel",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  time_index AS \"time\",\r\n  entity_id AS metric,\r\n  lat, long\r\nFROM $vehicle_table t\r\nWHERE\r\n  $__timeFilter(time_index) and t.entity_id = '${vehicle_device:raw}'\r\nORDER BY 1 DESC\r\nLIMIT 1"
      }
     ]
    }
   ]
  }
 ]
}