# config file version
apiVersion: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  - id: 1
    uid: P0DE374AC66335B6C
    orgId: 1
    name: CrateDB
    type: postgres
    typeName: PostgreSQL
    typeLogoUrl: public/app/plugins/datasource/postgres/img/postgresql_logo.svg
    access: proxy
    url: crate-db:5432
    user: crate
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      database: mtsmartufc
      sslmode: disable
    readOnly: false
  - id: 2
    uid: PBFA97CFB590B2093
    orgId: 1
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    basicAuthUser: admin
    basicAuthPassword: foobar
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData:
      tlsCACert: "..."
      tlsClientCert: "..."
      tlsClientKey: "..."
    version: 1
    editable: true