global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['crate-db:7071']
  - job_name: sql_exporter
    static_configs:
      - targets: [ 'sql-exporter:9237' ]